### ISSUE TITLE
Hyperspy UI does not work with Hyperspyv1.4

### ISSUE THREAD

**Issue by k8macarthur** [hyperspy/hyperspyUI#170]
When updating from 1.3 to 1.4 the UI no longer opens.

**Comment by dmlundeby** [comment]
Doesn't work for me either. The process shuts down with "ImportError: cannot import name 'BaseSignal' when running ´python -m hyperspyui´

Traceback (most recent call last):
  File "C:\Users\danie\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\danie\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspyui\__main__.py", line 151, in <module>
    main()
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspyui\__main__.py", line 129, in main
    from hyperspyui.mainwindow import MainWindow
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspyui\mainwindow.py", line 45, in <module>
    from hyperspyui.mainwindowhyperspy import MainWindowHyperspy, tr
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspyui\mainwindowhyperspy.py", line 36, in <module>
    from . import hooksignal
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspyui\hooksignal.py", line 24, in <module>
    import hyperspy.signal
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspy\signal.py", line 37, in <module>
    from hyperspy.drawing import mpl_hie, mpl_hse, mpl_he
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspy\drawing\mpl_hie.py", line 19, in <module>
    from hyperspy.drawing import image
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspy\drawing\image.py", line 31, in <module>
    from hyperspy.signal_tools import ImageContrastEditor
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspy\signal_tools.py", line 33, in <module>
    from hyperspy import components1d
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspy\components1d.py", line 46, in <module>
    from hyperspy._components.power_law import PowerLaw
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspy\_components\power_law.py", line 24, in <module>
    from hyperspy import signals
  File "C:\Users\danie\Anaconda3\lib\site-packages\hyperspy\signals.py", line 42, in <module>
    from hyperspy.signal import BaseSignal
ImportError: cannot import name 'BaseSignal'

**Comment by paddyh087** [comment]
Has this been resolved?

**Comment by ericpre** [comment]
Yes, it has been fixed in https://github.com/hyperspy/hyperspy/pull/2054 and this will be included in the next release. In the mean time, if you want to use HyperSpyUI, you can either downgrade hyperspy to 1.3 or use a development branch of hyperspy (RELEASE_next_path).
